#[derive(Debug, Clone)]
pub enum Action {
    FocusChange,
    ShowPlayerPicker(String, Option<String>),
    LaunchPlayer(crate::tui::state::PlayerKind, String, Option<String>),
    Tick,
    Key(crossterm::event::KeyEvent),
    Quit,
    GoBack,
    SelectLanguage(usize),
    Resize(u16, u16),
    ToggleHelp,
    ToggleTvMode,
    ShowTvWizard,
    TvChannelsLoaded(Vec<crate::providers::iptv_org::m3u::Channel>),
    Search {
        query: String,
        force_refresh: bool,
    },
    SelectSuggestion {
        query: String,
    },
    SearchSuccess {
        query: String,
        payload: serde_json::Value,
    },
    SearchFailure(String),
    FetchHomepage {
        tab_id: String,
        page: usize,
    },
    HomepageSuccess {
        tab_id: String,
        page: usize,
        payload: serde_json::Value,
    },
    HomepageFailure(String),
    Suggest(String),
    SuggestSuccess(String, serde_json::Value),
    MoveUp,
    MoveDown,
    MoveLeft,
    MoveRight,
    Submit,
    TabPane,
    FetchPreview(String),
    PreviewSuccess(String, serde_json::Value),
    PreviewFailure(String),
    PlayStream(bool),
    ShowSubtitlePopup(String, serde_json::Value, bool),
    ShowDownloadSubtitlePopup(serde_json::Value),
    LaunchMpv(String, Option<String>),
    PlayersDetected(Vec<crate::tui::state::PlayerKind>),
    DownloadStream(Option<String>),
    UpdateDownload(Option<f64>, Option<String>),
    CancelDownload,
    PromptDownloadEpisode,
    ConfirmDownloadEpisode,
    PromptDownloadSeason,
    ConfirmDownloadSeason,
    ProcessDownloadQueue,
    FetchDetails(String, bool),
    DetailsSuccess(String, serde_json::Value),
    DetailsFailure(String),
    InitStreamPool(String),
    StreamPoolInitialized(String, Vec<u32>),
    FetchEpisodeStreams {
        subject_id: String,
        season: usize,
        episode: usize,
        force_refresh: bool,
    },
    EpisodeStreamsReady(String, usize, usize, serde_json::Value),
    EpisodeStreamsFailed(String, usize, usize, String),
    PosterSuccess(String, std::sync::Arc<image::DynamicImage>),
    SearchPosterLoaded(String, Option<std::sync::Arc<image::DynamicImage>>),
    UpdateAvailable(String),
    CheckForUpdates,
    StartUpdate,
    UpdateProgress(f64),
    UpdateSuccess,
    UpdateFailure(String),
    SetStatus(String),
    Refresh,
    ClearCache,
}
