blank_issues_enabled: false
contact_links:
  - name: Ask a question
    url: https://github.com/mesamirh/MovieBox-Tui/discussions/new?category=q-a
    about: Ask questions, troubleshoot, or discuss MovieBox-Tui
